extends:
    - eslint:recommended
    - "plugin:react/recommended"
rules:
    no-console: 1
parserOptions:
    ecmaVersion: 6
    sourceType: module
    ecmaFeatures:
        jsx: true
env:
    browser: true
plugins:
    - react